# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_minimizer <- function(feval, geval, docall, x0, fargs, tol, maxnfeval, maxiter, decr_lnsrch, lnsrch_const, max_ls, extra_nonneg_tol, nthreads, verbose) {
    .Call(`_nonneg_cg_run_minimizer`, feval, geval, docall, x0, fargs, tol, maxnfeval, maxiter, decr_lnsrch, lnsrch_const, max_ls, extra_nonneg_tol, nthreads, verbose)
}

